### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by qhq**
My translation of the Chinese version, I think liveasx's version is not very good.

### CODE REVIEW

**Comment by MohammadAG** [comment]
Translations go in their respective directory. For example values-ar for Arabic, please see how livesax did the translation and update your commit.
Basically, res/vales/strings.xml should not be changed.

**Comment by qhq** [comment]
is it ok now?

**Comment by MohammadAG** [comment]
No, you're still doing the changes the main file.

**Comment by MohammadAG** [comment]
I checked your repo, you fixed it there. Just update the pull request.

**Comment by qhq** [comment]
Can you tell me what to do in detail

**Comment by MohammadAG** [comment]
Merged manually.

**Pull request closed without merging**
